# configures set up for android
#
# Example usage:
#   
#   cmake -DCMAKE_TOOLCHAIN_FILE=../soc-2012-swiss_cheese/build_files/cmake/config/blender_android.cmake  ../soc-2012-swiss_cheese -DTOOLCHAIN_PATH=/your_toolchain_path/a9tc

#


# Android is very simular to Linux as it is based on linux kernel
set(CMAKE_SYSTEM_NAME Linux)

add_definitions(-DUNIX)

set(CMAKE_CXX_COMPILER	${TOOLCHAIN_PATH}/bin/arm-linux-androideabi-g++)
set(CMAKE_C_COMPILER	${TOOLCHAIN_PATH}/bin/arm-linux-androideabi-gcc)
set(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(WITH_ANDROID             ON CACHE FORCE BOOL)
set(WITH_ASLIB               ON CACHE FORCE BOOL)


set(WITH_BUILTIN_GLEW        ON CACHE FORCE BOOL)
set(WITH_GAMEENGINE          ON CACHE FORCE BOOL)
set(WITH_PLAYER              ON CACHE FORCE BOOL)
set(WITH_SDL                 ON CACHE FORCE BOOL)
set(WITH_GHOST_SDL           ON CACHE FORCE BOOL)

set(WITH_BUILDINFO           OFF CACHE FORCE BOOL)
set(WITH_BULLET              OFF CACHE FORCE BOOL)
set(WITH_CODEC_FFMPEG        OFF CACHE FORCE BOOL)
set(WITH_CODEC_SNDFILE       OFF CACHE FORCE BOOL)
set(WITH_CYCLES              OFF CACHE FORCE BOOL)
set(WITH_FFTW3               OFF CACHE FORCE BOOL)
set(WITH_LIBMV               OFF CACHE FORCE BOOL)
set(WITH_CARVE               OFF CACHE FORCE BOOL)
set(WITH_IK_ITASC            OFF CACHE FORCE BOOL)
set(WITH_IMAGE_CINEON        OFF CACHE FORCE BOOL)
set(WITH_IMAGE_DDS           OFF CACHE FORCE BOOL)
set(WITH_IMAGE_FRAMESERVER   OFF CACHE FORCE BOOL)
set(WITH_IMAGE_HDR           OFF CACHE FORCE BOOL)
set(WITH_IMAGE_OPENEXR       OFF CACHE FORCE BOOL)
set(WITH_IMAGE_OPENJPEG      OFF CACHE FORCE BOOL)
set(WITH_IMAGE_REDCODE       OFF CACHE FORCE BOOL)
set(WITH_IMAGE_TIFF          OFF CACHE FORCE BOOL)
set(WITH_INPUT_NDOF          OFF CACHE FORCE BOOL)
set(WITH_INTERNATIONAL       OFF CACHE FORCE BOOL)
set(WITH_JACK                OFF CACHE FORCE BOOL)
set(WITH_LZMA                OFF CACHE FORCE BOOL)
set(WITH_LZO                 OFF CACHE FORCE BOOL)
set(WITH_MOD_BOOLEAN         OFF CACHE FORCE BOOL)
set(WITH_MOD_DECIMATE        OFF CACHE FORCE BOOL)
set(WITH_MOD_FLUID           OFF CACHE FORCE BOOL)
set(WITH_MOD_REMESH          OFF CACHE FORCE BOOL)
set(WITH_MOD_SMOKE           OFF CACHE FORCE BOOL)
set(WITH_MOD_OCEANSIM        OFF CACHE FORCE BOOL)
set(WITH_AUDASPACE           ON CACHE FORCE BOOL)
set(WITH_OPENAL              OFF CACHE FORCE BOOL)
set(WITH_OPENCOLLADA         OFF CACHE FORCE BOOL)
set(WITH_OPENMP              OFF CACHE FORCE BOOL)
set(WITH_PYTHON_INSTALL      OFF CACHE FORCE BOOL)
set(WITH_RAYOPTIMIZATION     OFF CACHE FORCE BOOL)
set(WITH_X11_XINPUT          OFF CACHE FORCE BOOL)
set(WITH_X11_XF86VMODE       OFF CACHE FORCE BOOL)
