#!/usr/bin/python
Import ('env')

sources = env.Glob('intern/*.cpp')
sources += env.Glob('intern/util/*.cpp')
sources += env.Glob('intern/source/*.cpp')

incs = ''
defs = ' DDF_GLUTGUI=0 '

if env['WITH_BF_OPENMP']:
    if env['OURPLATFORM'] == 'linuxcross':
        incs += ' ' + env['BF_OPENMP_INC']

    defs += ' DDF_OPENMP=1'

incs += ' ' + env['BF_PNG_INC'] + ' ' + env['BF_ZLIB_INC'] 
incs += ' intern intern/util intern/source  '


env.BlenderLib ('bf_intern_smoke', sources, Split(incs), Split(defs), libtype=['intern'], priority=[40] )
