Import ('env')

sources = env.Glob('*.cpp')

incs = ['.']
defs = ''

incs += Split(env['BF_OIIO_INC'])
incs += Split(env['BF_BOOST_INC'])

if env['OURPLATFORM'] in ('win32-vc', 'win32-mingw', 'linuxcross', 'win64-vc'):
    incs.append(env['BF_PTHREADS_INC'])

env.BlenderLib ('bf_intern_ptex', sources, Split(incs), Split(defs),
                libtype=['intern', 'player'], priority=[80, 200] )
